// Generated by CoffeeScript 1.8.0
var config, express, filePath, passport, path, utils;

path = require('path');

express = require('express');

passport = require('passport');

require('source-map-support').install();

require(path.join(__dirname, 'libs', 'utils')).setG(__dirname);

config = process.g.config;

utils = process.g.utils;

filePath = process.g.path;

require(filePath.db).connect(function(mongoose) {
  var app, logCtrl;
  app = express();
  require(filePath.passport)(passport);
  require(filePath.express)(app, passport, mongoose);
  require(filePath.router)(app);
  logCtrl = utils.getCtrl('log');
  logCtrl._registerAll();
  require(filePath.cron);
  return app.listen(app.get('port'), function() {
    return console.log("Listen on port " + (app.get('port')));
  });
});

//# sourceMappingURL=server.js.map
