// Generated by CoffeeScript 1.7.1
var DaoBase, fs, models, path, _;

path = require('path');

fs = require('fs-extra');

_ = require('lodash');

DaoBase = require(path.join(__dirname, 'DaoBase'));

models = require(process.g.modelsPath);

_.each(models, function(model, index) {
  var daoPath;
  daoPath = path.join(__dirname, 'mapping', index + '.js');
  if (fs.existsSync(daoPath)) {
    return module.exports[index] = _.extend(DaoBase.getInstance(model), require(daoPath));
  } else {
    return module.exports[index] = DaoBase.getInstance(model);
  }
});
