// Generated by CoffeeScript 1.7.1
var api, path;

path = require('path');

api = require(path.join(process.g.controllersPath, 'mapping', 'api'));

module.exports = function(app, mw) {
  app.get('/api', api.index);
  return app.get('/api/:module', api.getContent);
};
