// Generated by CoffeeScript 1.7.1
var back, utils;

utils = process.g.utils;

back = utils.getCtrl('back');

module.exports = function(app, mw) {
  app.get('/back', function(req, res, next) {
    return req.requireAuthorization(req, res, next);
  }, back.index);
  return app.get('/back/:module', back.getContent);
};
