// Generated by CoffeeScript 1.7.1
var ctrl, path;

path = require('path');

ctrl = require(path.join(process.g.controllersPath, 'mapping', 'index'));

module.exports = function(app, mw) {
  return app.get('/', mw.distribute);
};
