// Generated by CoffeeScript 1.7.1
var auth, ctrl, path;

path = require('path');

ctrl = require(path.join(process.g.controllersPath, 'mapping', 'index'));

auth = require(path.join(process.g.controllersPath, 'mapping', 'auth'));

module.exports = function(app, mw) {
  app.get('/', mw.distribute);
  app.post('/storage', ctrl.storage);
  app.get('/login', ctrl.list('login'));
  return app.post('/auth', auth.create);
};
