// Generated by CoffeeScript 1.7.1
var userModel;

userModel = require('mongoose').model('user');

module.exports = {
  getUserByID: function(userID, callback) {
    return userModel.findOne({
      _id: userID
    }, 'username email', callback);
  },
  getUserByEmail: function(email, callback) {
    return userModel.findOne({
      email: email
    }, 'username email', callback);
  }
};
