// Generated by CoffeeScript 1.7.1
var Model, modelName;

modelName = path.basename(__filename, '.js');

Model = require('mongoose').model(modelName);

module.exports = {
  list: function(query, options, callback) {
    return Model.find(query, '_id name token status ts').sort({
      ts: -1
    }).limit(options.perPage).skip(options.perPage * options.page).exec(callback);
  }
};

//# sourceMappingURL=app.map
