// Generated by CoffeeScript 1.7.1
var config, fs, markdown, path, viewsPath;

path = require('path');

fs = require('fs-extra');

markdown = require('markdown-js');

config = process.g.config;

viewsPath = process.g.viewsPath;

module.exports = {
  index: function(req, res) {
    return res.render('api/index.html', {
      nav: config.API.nav
    });
  },
  getContent: function(req, res) {
    var module, tplPath;
    module = req.params['module'];
    tplPath = path.join(viewsPath, 'api', 'tpl', module + '.md');
    return fs.exists(tplPath, function(exists) {
      var content, html_content;
      if (exists) {
        content = fs.readFileSync(tplPath, 'utf-8');
        html_content = markdown.parse(content);
        return res.send(html_content);
      } else {
        return res.send('tpl not exist');
      }
    });
  }
};
