// Generated by CoffeeScript 1.8.0
var APP_CONFIG, APP_STATUS, appDao, config, filePath, utils, _;

_ = require('lodash');

filePath = process.g.path;

config = process.g.config;

utils = process.g.utils;

appDao = require(filePath.daos).app;

APP_CONFIG = utils.getSchemaConfig('app');

APP_STATUS = APP_CONFIG.status.enumeration;

module.exports = {
  create: function(req, res) {
    var name, token, _id;
    _id = utils.createID(6);
    name = req.body.name || '';
    token = utils.createToken(name);
    return appDao.getOne({
      name: name
    }, function(err, app) {
      if (!err && !app) {
        return appDao.create({
          _id: _id,
          name: name,
          token: token
        }, function(err, raw) {
          if (!err) {
            return res.successMsg('应用授权成功');
          } else {
            return res.errorMsg(err || '应用授权失败');
          }
        });
      } else {
        return res.errorMsg(err || '应用已授权');
      }
    });
  },
  list: function(req, res) {
    var options, query;
    query = {
      status: APP_STATUS.enable
    };
    options = {};
    return appDao.list(query, options, function(err, apps) {
      if (!err) {
        return res.success(apps);
      } else {
        return res.errorMsg('授权列表获取失败');
      }
    });
  },
  _getByID: function(id, callback) {
    return appDao.getByID(id, callback);
  },
  _getOne: function(query, callback) {
    return appDao.getOne(query, callback);
  }
};
