// Generated by CoffeeScript 1.7.1
var authDao, crypto, fMd5, fToken;

crypto = require('crypto');

authDao = require(process.g.daoPath).auth;

fMd5 = function(text) {
  return crypto.createHash('md5').update(text).digest('hex');
};

fToken = function(appName, appID) {
  var nRandom, text;
  nRandom = Math.random();
  text = appID + nRandom + appName;
  return fMd5(text);
};

module.exports = {
  create: function(req, res) {
    var appName;
    appName = req.body.appName;
    return authDao.getOne({
      appName: appName
    }, function(err, auth) {
      if (!auth) {
        return authDao.count({}, function(err, amount) {
          var appID, token;
          appID = Number(amount) + 1;
          token = fToken(appName, appID);
          return authDao.create({
            appName: appName,
            appID: appID,
            token: token
          }, function(err, raw) {
            if (!err) {
              return res.requestSucceed({
                appID: appID,
                token: token
              });
            } else {
              return res.requestError('授权失败');
            }
          });
        });
      } else {
        return res.requestError('appName已存在');
      }
    });
  },
  get: function(query, callback) {
    return authDao.getOne(query, callback);
  }
};
