// Generated by CoffeeScript 1.7.1
var auth, config, fs, path, utils, viewsPath, _;

path = require('path');

fs = require('fs-extra');

_ = require('lodash');

config = process.g.config;

utils = process.g.utils;

auth = utils.getCtrl('auth');

viewsPath = process.g.viewsPath;

module.exports = {
  index: function(req, res) {
    return auth.listAuth(function(err, auths) {
      var aDynamicNav, nav;
      aDynamicNav = [];
      nav = config.BACK.nav;
      if (!err) {
        _.each(auths, function(auth) {
          return aDynamicNav.push({
            name: auth.appID,
            title: auth.appName
          });
        });
      }
      nav = nav.concat(aDynamicNav);
      return res.render('back/index.html', {
        nav: nav
      });
    });
  },
  getContent: function(req, res) {
    var module;
    module = req.params['module'];
    if (module === 'auth') {
      return auth.listAuth(function(err, oAuthList) {
        console.log(oAuthList);
        return res.render('back/auth.html', {
          oAuthList: oAuthList
        });
      });
    }
  }
};
