// Generated by CoffeeScript 1.7.1
var config, fs, logger, mongoose, path, storage, utils, _;

fs = require('fs');

path = require('path');

_ = require('lodash');

mongoose = require('mongoose');

config = process.g.config;

utils = process.g.utils;

logger = require(path.join(__dirname, 'log'));

storage = require(path.join(__dirname, 'storage'));

require(process.g.modelsPath);

module.exports = {
  fWriteLog: function(req, res) {
    var fWriteLog, sModel;
    sModel = req.type;
    if (!require('mongoose').models[sModel]) {
      res.error('日志类型不存在，请先创建');
    }
    fWriteLog = new logger(sModel);
    return fWriteLog(req.query, function(err) {
      if (!err) {
        return res.success('数据提交成功');
      } else {
        return res.error('数据提交失败');
      }
    });
  },
  storage: function(req, res) {
    return storage(function(err) {
      if (!err) {
        return res.success('数据已经被更新');
      } else {
        return res.error('数据更新失败');
      }
    }, true);
  },
  list: function(model) {
    return function(req, res) {
      var Model, criteria, page, perPage;
      page = (req.param('page') || 0) > 0 ? req.param('page') : 1;
      perPage = config.PERPAGE;
      criteria = {
        query: {},
        options: {
          page: page - 1,
          perPage: perPage
        }
      };
      Model = mongoose.model(model);
      return Model.find({}, function(err, logs) {
        if (!err) {
          return res.success(logs);
        } else {
          return res.error('获取列表失败');
        }
      });
    };
  }
};
