// Generated by CoffeeScript 1.7.1
var fs, logsPath, path, utils;

path = require('path');

fs = require('fs-extra');

utils = process.g.utils;

logsPath = process.g.logsPath;

module.exports = function(logName) {
  var fileName;
  fileName = logName + '.' + utils.getTime() + '.log';
  return function(message) {
    message = JSON.stringify(message, null, 0) + '\n';
    return fs.writeFileSync(path.join(logsPath, fileName), message, {
      encoding: 'utf8',
      flag: 'a'
    });
  };
};
