// Generated by CoffeeScript 1.7.1
var Schema, config, mongoose, utils, _;

mongoose = require('mongoose');

Schema = mongoose.Schema;

_ = require('lodash');

config = process.g.config;

utils = process.g.utils;

module.exports = function(sModelName, oSchema) {
  var schema;
  oSchema.timestamp = Date;
  schema = new Schema(oSchema);
  return mongoose.model(sModelName, schema);
};
