// Generated by CoffeeScript 1.8.0
var BackupDB, CronJob, DB, after10s, async, config, d, fs, hour, jobBackupDB, minute, moment, path, second, utils;

path = require('path');

fs = require('fs-extra');

CronJob = require('cron').CronJob;

async = require('async');

moment = require('moment');

config = process.g.config;

utils = process.g.utils;

DB = config.APP.DB;

BackupDB = require(path.join(process.g.rootPath, 'tools', 'db-backup', 'index.js'));

d = moment().add(10, 'seconds');

hour = d.hours();

minute = d.minutes();

second = d.seconds();

after10s = "" + second + " " + minute + " " + hour + " * * *";

jobBackupDB = new CronJob(after10s, function() {
  var dbBackupPath;
  dbBackupPath = path.join(process.g.rootPath, '..', 'logger_backup', 'db');
  fs.ensureDirSync(dbBackupPath);
  console.log(dbBackupPath);
  console.log(DB.host + ':' + DB.port);
  console.log(DB.name);
  return BackupDB.init({
    path: dbBackupPath,
    host: DB.host + ':' + DB.port,
    name: DB.name + '_' + process.env.NODE_ENV
  });
}, null, true, 'Asia/Shanghai');

//# sourceMappingURL=cron.js.map
