// Generated by CoffeeScript 1.7.1
var CronJob, config, path, request, storage, store;

path = require('path');

storage = require(path.join(process.g.controllersPath, 'mapping', 'storage'));

CronJob = require('cron').CronJob;

request = require('request');

config = process.g.config;

store = new CronJob(config.STORAGE_CRON, function() {
  return storage(function(err) {
    if (err) {
      return console.log(err);
    }
  });
}, null, true, 'Asia/Shanghai');
