// Generated by CoffeeScript 1.7.1
var CronJob, config, path, request, storage, store, utils;

path = require('path');

CronJob = require('cron').CronJob;

request = require('request');

config = process.g.config;

utils = process.g.utils;

storage = utils.getCtrl('storage');

if (config.STORAGE.cron) {
  store = new CronJob(config.STORAGE.cron, function() {
    return storage.start();
  }, null, true, 'Asia/Shanghai');
}
