// Generated by CoffeeScript 1.7.1
var config, env, express;

env = process.env.NODE_ENV || 'dev';

express = require('express');

config = process.g.config;

module.exports = function(app, mongoose) {
  var hbs;
  if (app.get('env') === 'dev') {
    app.use(express.errorHandler());
    app.set('view cache', false);
    app.use(express.logger('dev'));
  }
  app.use(function(req, res, next) {
    res.requestError = function(data) {
      return res.json({
        status: 0,
        message: data
      });
    };
    res.requestSucceed = function(data) {
      return res.json({
        status: 1,
        message: data
      });
    };
    return next();
  });
  app.set('port', config.PORT);
  app.set('views', process.g.viewsPath);
  app.set('view engine', 'html');
  app.engine('html', require('hbs').__express);
  app.use(express.compress({
    filter: function(req, res) {
      return /json|text|javascript|css/.test(res.getHeader('Content-Type'));
    },
    level: 9
  }));
  app.use(express.json());
  app.use(express.urlencoded());
  app.use(require('connect-multiparty')());
  app.use(express.cookieParser());
  app.use(express.methodOverride());
  app.enable('jsonp callback');
  app.use(app.router);
  app.use(express["static"](process.g.publicPath));
  hbs = require('hbs');
  return hbs.registerPartials(path.join(process.g.viewsPath, 'back', 'base'));
};
