// Generated by CoffeeScript 1.7.1
var basicAuth, config, env, express;

env = process.env.NODE_ENV || 'dev';

express = require('express');

basicAuth = require('connect-basic-auth');

config = process.g.config;

module.exports = function(app, mongoose) {
  var hbs;
  if (app.get('env') === 'dev') {
    app.use(express.errorHandler());
    app.set('view cache', false);
    app.use(express.logger('dev'));
  }
  app.use(function(req, res, next) {
    res.error = function(data) {
      return res.json({
        code: data.code || 400,
        msg: data
      });
    };
    res.success = function(data) {
      return res.json({
        code: 200,
        msg: data
      });
    };
    return next();
  });
  app.set('port', config.PORT);
  app.set('views', process.g.viewsPath);
  app.set('view engine', 'html');
  app.engine('html', require('hbs').__express);
  app.use(express.compress({
    filter: function(req, res) {
      return /json|text|javascript|css/.test(res.getHeader('Content-Type'));
    },
    level: 9
  }));
  app.use(basicAuth(function(credentials, req, res, next) {
    if (credentials && credentials.username === "node" && credentials.password === "log") {
      return next();
    } else {
      if (!credentials) {
        console.log("credentials not provided");
      }
      if (credentials && credentials.username) {
        console.log("credentials-username:" + credentials.username);
      }
      if (credentials && credentials.password) {
        console.log("credentials-password:" + credentials.username);
      }
      return next("Unautherized!");
    }
  }));
  app.use(express.json());
  app.use(express.urlencoded());
  app.use(require('connect-multiparty')());
  app.use(express.cookieParser());
  app.use(express.methodOverride());
  app.enable('jsonp callback');
  app.use(app.router);
  app.use(express["static"](process.g.publicPath));
  hbs = require('hbs');
  hbs.registerPartials(path.join(process.g.viewsPath, 'back', 'base'));
  return hbs.registerHelper('trList', function(items, options) {
    var item, key, out, value, _i, _len;
    out = '';
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      item = items[_i];
      out += '<tr>';
      for (key in item) {
        value = item[key];
        out += '<td>' + value + '</td>';
      }
      out += '</tr>';
    }
    return out;
  });
};
