// Generated by CoffeeScript 1.7.1
var LocalStrategy;

LocalStrategy = require('passport-local').Strategy;

module.exports = function(passport) {
  passport.serializeUser(function(user, done) {
    return done(null, user);
  });
  return passport.deserializeUser(function(user, done) {
    return done(null, user);
  });
};
