// Generated by CoffeeScript 1.7.1
var config, ctrl, filePath, fs, mw, path, routesConfigPath, routesDirPath, routesMWPath, routesPath, utils, _;

path = require('path');

fs = require('fs-extra');

_ = require('lodash');

config = process.g.config;

utils = process.g.utils;

filePath = process.g.path;

routesDirPath = filePath.routes;

routesConfigPath = path.join(routesDirPath, 'config');

routesPath = path.join(routesDirPath, 'mapping');

routesMWPath = path.join(routesDirPath, 'middlewares');

mw = require(routesMWPath);

ctrl = require(filePath.controllers);

module.exports = function(app) {
  return _.forEach(fs.readdirSync(routesPath), function(routesFileName, index) {
    var ctrlName, routesFilePath;
    if (~routesFileName.indexOf('.js')) {
      ctrlName = routesFileName.replace('.js', '');
      routesFilePath = path.join(routesPath, routesFileName);
      return require(routesFilePath)(app, mw, ctrl != null ? ctrl[ctrlName] : void 0);
    }
  });
};

//# sourceMappingURL=router.map
