// Generated by CoffeeScript 1.7.1
var fs, moment, path, _;

path = require('path');

fs = require('fs');

_ = require('lodash');

moment = require('moment');

module.exports = {
  getTime: function(date) {
    var config, time;
    config = process.g.config;
    time = moment(date).utc().zone(-8).format("YYYYMMDDHHmm");
    return time = time - time % config.LOG_INTERVAL;
  },
  setG: function(rootPath) {
    var appPath, configPath, libs, libsPath, logsPath;
    configPath = path.join(rootPath, 'config');
    appPath = path.join(rootPath, 'app');
    libsPath = path.join(rootPath, 'libs');
    logsPath = path.join(rootPath, 'logs');
    process.g = {
      config: require(configPath),
      rootPath: rootPath,
      configPath: configPath,
      appPath: appPath,
      libsPath: libsPath,
      logsPath: logsPath
    };
    _.each(fs.readdirSync(appPath), function(dir, index) {
      var dirPath;
      dirPath = path.join(appPath, dir);
      return process.g[dir + 'Path'] = dirPath;
    });
    libs = {};
    _.each(fs.readdirSync(libsPath), function(file, index) {
      var fileName;
      if (~file.indexOf('.js')) {
        fileName = file.replace('.js', '');
        return libs[fileName] = path.join(libsPath, file);
      }
    });
    process.g.libs = libs;
    return process.g.utils = require(libs.utils);
  }
};
