// Generated by CoffeeScript 1.7.1
var config, daoBase, daosPath, filePath, fs, models, path, utils, _;

path = require('path');

fs = require('fs-extra');

_ = require('lodash');

config = process.g.config;

utils = process.g.utils;

filePath = process.g.path;

daosPath = path.join(filePath.daos, 'mapping');

daoBase = require(path.join(__dirname, 'daoBase'));

models = require(filePath.models);

_.forEach(models, function(Model, modelName) {
  var daoFilePath, modelFileName;
  modelFileName = modelName + '.js';
  daoFilePath = path.join(daosPath, modelFileName);
  if (fs.existsSync(daoFilePath)) {
    return module.exports[modelName] = _.extend(daoBase.getInstance(Model), require(daoFilePath));
  } else {
    return module.exports[modelName] = daoBase.getInstance(Model);
  }
});

//# sourceMappingURL=index.map
