// Generated by CoffeeScript 1.7.1
var ctrlsPath, fs, path, _;

path = require('path');

fs = require('fs-extra');

_ = require('lodash');

ctrlsPath = path.join(__dirname, 'mapping');

_.each(fs.readdirSync(ctrlsPath), function(ctrlFile, index) {
  var ctrlName, ctrlPath;
  if (~ctrlFile.indexOf('.js')) {
    ctrlName = ctrlFile.replace('.js', '');
    ctrlPath = path.join(ctrlsPath, ctrlFile);
    return module.exports[ctrlName] = require(ctrlPath);
  }
});
