// Generated by CoffeeScript 1.7.1
var Schema, fs, modelsPath, mongoose, oAttrValueMap, path, utils, _;

fs = require('fs');

path = require('path');

_ = require('lodash');

mongoose = require('mongoose');

Schema = mongoose.Schema;

modelsPath = path.join(__dirname, 'mapping');

utils = process.g.utils;

oAttrValueMap = {
  String: String,
  Date: Date
};

_.each(fs.readdirSync(modelsPath), function(file, index) {
  var sModel;
  require(path.join(modelsPath, file));
  sModel = file.replace('.js', '');
  module.exports[sModel] = mongoose.model(sModel);
});
