// Generated by CoffeeScript 1.8.0
var Schema, config, filePath, fs, modelConfigPath, modelMappingPath, mongoose, path, utils, _;

fs = require('fs');

path = require('path');

_ = require('lodash');

mongoose = require('mongoose');

Schema = mongoose.Schema;

config = process.g.config;

utils = process.g.utils;

filePath = process.g.path;

modelConfigPath = path.join(__dirname, 'config');

modelMappingPath = path.join(__dirname, 'mapping');

_.forEach(fs.readdirSync(modelMappingPath), function(modelFileName, index) {
  var modelName;
  modelName = modelFileName.replace('.js', '');
  require(path.join(modelMappingPath, modelFileName));
  return module.exports[modelName] = mongoose.model(modelName);
});
